"use client";
import Link from 'next/link';
import { useState } from 'react';
import { ScreenHeader } from '@/components/screen-header';
import { ArenaFeedback } from '@/components/arena-feedback';
import { useArena } from '@/lib/use-arena';
import type { Tournament } from '@/lib/arena';
export function TournamentRoom({ id }: { id: string }) {
 const { data: t, loading, error, busy, mutate } = useArena<Tournament>('tournament', 'tournament', id);
 const [selectedRound, setSelectedRound] = useState<string>('all');
 const joined = t?.players.some(p => p.id === t.me);
 const mine = t?.matches.find(m => m.status === 'running' && m.players.some(p => p.id === t.me));
 return <main className="page-wrap page-lobby"><ScreenHeader title={t?.name || 'Tournament'} kicker={t?.status || 'EVENT'} description="Register, meet the table, and follow every round." action={<Link className="button button-secondary" href="/tournaments">All events</Link>} /><ArenaFeedback error={error} loading={loading} />
  {t && <><div className="lobby-grid"><section className="panel lobby-panel"><h2>The roster</h2><p>{t.players.length} / {t.maxPlayers} players · {new Date(t.startsAt).toLocaleString()}</p><div className="roster">{t.players.map(p => <div className="roster-row" key={p.id}><strong>{p.name}{p.id === t.me ? ' · you' : ''}</strong><span>{p.status === 'winner' ? '🏆 Champion' : p.status}</span></div>)}</div>
  {t.status === 'registration' && <div className="button-row"><button className="button button-primary" disabled={busy || (!joined && t.players.length >= t.maxPlayers)} onClick={() => mutate(joined ? 'withdrawTournament' : 'joinTournament')}>{joined ? 'Withdraw registration' : 'Join tournament'}</button>{t.host === t.me && <button className="button button-secondary" disabled={busy || t.players.length < 2} onClick={() => mutate('startTournament')}>Start bracket</button>}</div>}
  {mine && <Link className="button button-primary" href={`/game?match=${mine.id}`}>Play your match →</Link>}{joined && t.status === 'running' && !mine && <p role="status">Your result is saved. Follow the bracket below for your next match.</p>}
  </section><aside className="panel rules-panel"><h3>Published rules</h3><ul><li>Single elimination · random pairing · automatic byes</li><li>{t.rules.gameType === 'knockout' ? `${t.rules.targetScore}-point series per match` : 'One round per match'}</li><li>{t.rules.initialHand}-card deal</li><li>Pick Two: {t.rules.pickTwoEnabled ? t.rules.pickTwoMode : 'off'}</li><li>Pick Three: {t.rules.pickThreeEnabled ? t.rules.pickThreeMode : 'off'}</li><li>{t.rules.turnTimer === 'off' ? 'Untimed' : `${t.rules.turnTimer}-second turns`}</li></ul>{t.host === t.me && t.status === 'registration' && <button className="button button-secondary" disabled={busy} onClick={() => { if (confirm('Cancel this tournament?')) void mutate('cancelTournament'); }}>Cancel event</button>}</aside></div>
  {t.matches.length > 0 && <section className="panel lobby-panel" style={{ marginTop: 24 }}><h2>Bracket</h2><label htmlFor="bracket-round">Round</label><select className="form-input" id="bracket-round" value={selectedRound} onChange={event => setSelectedRound(event.target.value)}><option value="all">All rounds</option>{Array.from(new Set(t.matches.map(m => m.round))).map(round => <option key={round} value={String(round)}>Round {round}</option>)}</select><div className="bracket-grid">{Array.from(new Set(t.matches.map(m => m.round))).filter(round => selectedRound === 'all' || String(round) === selectedRound).map(round => <div key={round}><h3>Round {round}</h3>{t.matches.filter(m => m.round === round).map(m => <article className="bracket-match" key={m.id}>{m.players.map(p => <p key={p.id}><strong>{p.name}</strong>{m.winner === p.id ? ' · Winner' : ''}</p>)}<small>{m.players.length === 1 ? 'Bye' : m.status}</small>{m.players.some(p => p.id === t.me) && <Link className="text-link" href={`/game?match=${m.id}`}>{m.status === 'running' ? 'Play' : 'Result'} →</Link>}</article>)}</div>)}</div></section>}</>}
 </main>;
}
