export const MOCK_ROOMS = [
  {
    name: "Friday Night Heat",
    host: "Tayo",
    players: 3,
    maxPlayers: 5,
    tags: ["Classic", "Stack 2/5"],
    status: "Open",
    initials: ["T", "A", "K"],
  },
  {
    name: "No Mercy, No Whot",
    host: "Mide",
    players: 2,
    maxPlayers: 4,
    tags: ["100 Knockout", "10 sec"],
    status: "Open",
    initials: ["M", "Z"],
  },
  {
    name: "The Angle Table",
    host: "Chidi",
    players: 4,
    maxPlayers: 5,
    tags: ["Tournament", "Private"],
    status: "Starting soon",
    initials: ["C", "N", "D", "O"],
  },
];

export const MOCK_TOURNAMENTS = [
  {
    id: "lagos-after-dark",
    day: "12",
    month: "SEP",
    title: "Lagos After Dark",
    description: "5-player elimination · knockout rounds",
    time: "9:00 PM WAT",
    players: "18 / 32 joined",
    prize: "Bragging rights",
    status: "Open",
  },
  {
    id: "abuja-angles",
    day: "14",
    month: "SEP",
    title: "Abuja Angles",
    description: "Classic Nigerian rules · stacking enabled",
    time: "7:30 PM WAT",
    players: "9 / 16 joined",
    prize: "Top table badge",
    status: "Open",
  },
  {
    id: "the-last-card",
    day: "20",
    month: "SEP",
    title: "The Last Card",
    description: "Quick rounds · semi-last calls required",
    time: "8:00 PM WAT",
    players: "32 / 32 joined",
    prize: "Waitlist available",
    status: "Full",
  },
];
